
package Home;
import gestionm.GestionM;
import gestionm.Fournisseur;
import java.awt.Color;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class intervantion extends javax.swing.JFrame {
  
    public intervantion() {
        initComponents();
        Border borderLabel = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.green);
        SerieMateriel.setBorder(borderLabel);
        DateIntervention.setBorder(borderLabel);
        NomTechnicien.setBorder(borderLabel);
        PrenomTechnicien.setBorder(borderLabel);
        TelTechnicien.setBorder(borderLabel);
        Description.setBorder(borderLabel);
        Solution.setBorder(borderLabel);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel soulution = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane6 = new javax.swing.JScrollPane();
        Solution = new javax.swing.JTextPane();
        javax.swing.JLabel prenom = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        PrenomTechnicien = new javax.swing.JTextPane();
        javax.swing.JButton AjouterIntervention = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel serie = new javax.swing.JLabel();
        javax.swing.JLabel description = new javax.swing.JLabel();
        SerieMateriel = new javax.swing.JComboBox();
        javax.swing.JScrollPane jScrollPane4 = new javax.swing.JScrollPane();
        Description = new javax.swing.JTextArea();
        javax.swing.JLabel nom = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        NomTechnicien = new javax.swing.JTextPane();
        javax.swing.JLabel phone = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane5 = new javax.swing.JScrollPane();
        TelTechnicien = new javax.swing.JTextPane();
        javax.swing.JLabel date = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        DateIntervention = new javax.swing.JTextPane();
        javax.swing.JScrollPane jScrollPane8 = new javax.swing.JScrollPane();
        tableIntr = new javax.swing.JTable();
        javax.swing.JButton btndelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnlisteMtr = new javax.swing.JButton();
        btnFrn = new javax.swing.JButton();
        btnIntr = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        soulution.setText("SOULUTION");

        Solution.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Solution.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane6.setViewportView(Solution);

        prenom.setText("PRENOM");

        PrenomTechnicien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PrenomTechnicien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(PrenomTechnicien);

        AjouterIntervention.setBackground(new java.awt.Color(0, 204, 204));
        AjouterIntervention.setText("Ajouter");
        AjouterIntervention.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AjouterInterventionMouseEntered(evt);
            }
        });
        AjouterIntervention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjouterInterventionActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ajouter Intervention");

        serie.setText("SERIE");

        description.setText("DESCRIPTION");

        SerieMateriel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SerieMateriel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SerieMateriel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerieMaterielActionPerformed(evt);
            }
        });

        Description.setColumns(20);
        Description.setRows(5);
        jScrollPane4.setViewportView(Description);

        nom.setText("NOM");

        NomTechnicien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NomTechnicien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(NomTechnicien);

        phone.setText("PHONE");

        TelTechnicien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TelTechnicien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane5.setViewportView(TelTechnicien);

        date.setText("DATE");

        DateIntervention.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DateIntervention.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(DateIntervention);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(serie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SerieMateriel, 0, 140, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AjouterIntervention, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soulution, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SerieMateriel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date)
                    .addComponent(prenom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(description)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(phone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(soulution)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addComponent(AjouterIntervention)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableIntr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "DESCRIPTION", "NOM", "PRENOM", "PHONE", "SOLUTION", "SERIE DE MATERIEL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableIntr.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane8.setViewportView(tableIntr);

        btndelete.setBackground(new java.awt.Color(204, 0, 51));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Home/delete-bin-5-line.png"))); // NOI18N
        btndelete.setText("Supprimer");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));

        btnlisteMtr.setBackground(new java.awt.Color(204, 204, 255));
        btnlisteMtr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionm/liste-de-controle.png"))); // NOI18N
        btnlisteMtr.setText("LISTE MATERIELS");
        btnlisteMtr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnlisteMtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlisteMtrActionPerformed(evt);
            }
        });

        btnFrn.setBackground(new java.awt.Color(204, 204, 255));
        btnFrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionm/fournisseur.png"))); // NOI18N
        btnFrn.setText("FOURNISEUR");
        btnFrn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrnActionPerformed(evt);
            }
        });

        btnIntr.setBackground(new java.awt.Color(204, 204, 255));
        btnIntr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionm/intervention.png"))); // NOI18N
        btnIntr.setText("INTERVENTION");
        btnIntr.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIntr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnlisteMtr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIntr, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnlisteMtr)
                .addGap(47, 47, 47)
                .addComponent(btnFrn)
                .addGap(60, 60, 60)
                .addComponent(btnIntr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Liste Intervention");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Intervention");

        jToggleButton1.setText("Materiels");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Deconnexion");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jToggleButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
                            .addComponent(btndelete))
                        .addGap(9, 9, 9))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete)
                        .addGap(127, 127, 127))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(61, 61, 61))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AjouterInterventionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjouterInterventionActionPerformed
        // TODO add your handling code here:
          // String serie = SerieMateriel.getText();
        String dateSaisie = DateIntervention.getText();
        String descriptionSaisie = Description.getText();
        String nomSaisie = NomTechnicien.getText();
        String prenomSaisie = PrenomTechnicien.getText();
        String phoneSaisie = TelTechnicien.getText();
        String solutionSaisie = Solution.getText();

        if (dateSaisie.equals("") || descriptionSaisie.equals("") || nomSaisie.equals("") || prenomSaisie.equals("") || phoneSaisie.equals("") || solutionSaisie.equals("")) {
            JOptionPane.showMessageDialog(this, "Veuillez saisir toutes les données !");
        } else {
            // Insérer les données dans la base de données après vérification
            insererDonnees(dateSaisie, descriptionSaisie, nomSaisie, prenomSaisie, phoneSaisie,solutionSaisie );
        }
    }//GEN-LAST:event_AjouterInterventionActionPerformed
   
    private void SerieMaterielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerieMaterielActionPerformed
    }//GEN-LAST:event_SerieMaterielActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
       
        DefaultTableModel tblModel = (DefaultTableModel) tableIntr.getModel();
    
    if (tableIntr.getSelectedRowCount() == 1) {
        // Récupérer l'indice de la ligne sélectionnée
        int selectedRow = tableIntr.getSelectedRow();
        // Récupérer l'identifiant de la ligne sélectionnée (par exemple, la première colonne)
        String id = tblModel.getValueAt(selectedRow, 0).toString(); // Assurez-vous que la première colonne contient l'identifiant
        
        // Supprimer la ligne de la base de données correspondant à l'identifiant
        supprimerLigneDeBaseDeDonnees(id);
        
        // Supprimer la ligne du modèle de tableau
        tblModel.removeRow(selectedRow);
    } else {
        if (tableIntr.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "La table est vide !");
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une ligne à supprimer !");
        }
    } 
    }//GEN-LAST:event_btndeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tableIntr.getModel();
    Vector<Vector> tableData = model.getDataVector();

    //Saving of object in a file
    try {
    FileOutputStream file = new FileOutputStream("file.bin");
    ObjectOutputStream output = new ObjectOutputStream(file);

    // Method for serialization of object
    output.writeObject(tableData);

    output.close();
    file.close();
    }
  catch (Exception ex) {
    ex.printStackTrace();
    }
         
        
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         try {
    // TODO add your handling code here:
    FileInputStream file = new FileInputStream("file.bin");
    ObjectInputStream input = new ObjectInputStream(file);
    // Method for deserialization of object
    Vector<Vector> tableData = (Vector<Vector>) input.readObject ();

    input.close();
    file.close();
            DefaultTableModel model = (DefaultTableModel) tableIntr.getModel();
        for (int i = 0; i < tableData.size(); i++){
        Vector row = tableData.get(i);
        model.addRow(new Object[]{row.get(0), row.get(1), row.get(2), row.get(3)}) ;
    }}
    catch (Exception ex) {
    ex.printStackTrace ();
    
    }
        
    }//GEN-LAST:event_formWindowOpened

    private void AjouterInterventionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AjouterInterventionMouseEntered

    }//GEN-LAST:event_AjouterInterventionMouseEntered

    private void btnlisteMtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlisteMtrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlisteMtrActionPerformed

    private void btnFrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Fournisseur fournisseur = new Fournisseur();
            fournisseur.setVisible(true);
            fournisseur.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnFrnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void btnIntrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntrActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        intervantion Intervantion = new intervantion();
            Intervantion.setVisible(true);
            Intervantion.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnIntrActionPerformed

     private void insererDonnees ( String dateSaisie, String descriptionSaisie,  String nomSaisie,  String prenomSaisie, String phoneSaisie,String solutionSaisie ) {
    String url = "jdbc:mysql://localhost:3306/gestionm";
    String user = "root";
    String pass = "";
    String sql = "INSERT INTO intervention (dateSaisie, descriptionSaisie, nomSaisie, prenomSaisie, phoneSaisie,solutionSaisie ) VALUES (?, ?, ?, ?, ?, ?)";

    try (Connection con = DriverManager.getConnection(url, user, pass);
         PreparedStatement pstmt = con.prepareStatement(sql)) {

        // Remplir les valeurs des paramètres de la requête
        pstmt.setString(1, dateSaisie);
        pstmt.setString(2, descriptionSaisie);
        pstmt.setString(3, nomSaisie);
        pstmt.setString(4, prenomSaisie);
        pstmt.setString(5, phoneSaisie);
        pstmt.setString(6, solutionSaisie);
        // Exécuter la requête
       int rowsInserted = pstmt.executeUpdate();
        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Données ajoutées avec succès !");
            
            // Mettre à jour le modèle de tableau pour afficher les nouvelles données
            DefaultTableModel model = (DefaultTableModel) tableIntr.getModel();
            // Ajouter une nouvelle ligne avec les données insérées
            model.addRow(new Object[]{dateSaisie, descriptionSaisie, nomSaisie, prenomSaisie, phoneSaisie,solutionSaisie});
        }
    } catch (SQLException ex) {
        System.out.println("Erreur lors de l'insertion des données : " + ex.getMessage());
    }
    }
     
    /*supprimer*/
     
    private void supprimerLigneDeBaseDeDonnees(String id) {
    String url = "jdbc:mysql://localhost:3306/gestionm";
    String user = "root";
    String pass = "";
    String sql = "DELETE FROM intervention WHERE nom = ?"; // Remplacez 'nom' par le nom de la colonne contenant l'identifiant
    
    try (Connection con = DriverManager.getConnection(url, user, pass);
         PreparedStatement pstmt = con.prepareStatement(sql)) {
        
        // Remplir les valeurs des paramètres de la requête
        pstmt.setString(1, id);
        
        // Exécuter la requête de suppression
        int rowsDeleted = pstmt.executeUpdate();
        if (rowsDeleted > 0) {
            System.out.println("Ligne supprimée de la base de données avec succès !");
        } else {
            System.out.println("Aucune ligne n'a été supprimée de la base de données !");
        }
        
    } catch (SQLException ex) {
        System.out.println("Erreur lors de la suppression de la ligne de la base de données : " + ex.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(intervantion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(intervantion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(intervantion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(intervantion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                intervantion intervantion =  new intervantion() ;
                intervantion.setVisible(true);
                intervantion.setLocationRelativeTo(null);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane DateIntervention;
    private javax.swing.JTextArea Description;
    private javax.swing.JTextPane NomTechnicien;
    private javax.swing.JTextPane PrenomTechnicien;
    private javax.swing.JComboBox SerieMateriel;
    private javax.swing.JTextPane Solution;
    private javax.swing.JTextPane TelTechnicien;
    private javax.swing.JButton btnFrn;
    private javax.swing.JButton btnIntr;
    private javax.swing.JButton btnlisteMtr;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable tableIntr;
    // End of variables declaration//GEN-END:variables
}
